// generate-nav.mjs
// Generates data/navigation.js from the entries in pages/, two levels deep:
// top-level items plus their direct children (used for the megamenus).
// Runs before `next dev` and `next build` (see package.json scripts).
// Usage: node generate-nav.mjs [--slug-to-exclude ...]
//   e.g. node generate-nav.mjs --draft --wip

import fs from 'fs';
import path from 'path';

const PAGES_DIR = path.join(process.cwd(), 'pages');
const OUTPUT_FILE = path.join(process.cwd(), 'data', 'navigation.js');

// Only these extensions produce routes. .css / .module.css / .json / .md etc. are ignored.
const PAGE_EXTENSIONS = ['.jsx', '.js', '.tsx', '.ts'];

// Next.js internals and non-navigable routes — always skipped.
// 'index' is the homepage: it's the fixed "Home" link in the navbar, never a generated item.
const ALWAYS_SKIP = new Set(['index', '_app', '_document', '_error', '404', '500', 'api', 'sitemap', 'robots']);

// Pages that exist as routes but must not appear in the top nav (legal pages live in the footer,
// Layout is a component).
const EXCLUDED = new Set([
  'Layout',
  'about',
  'cookie-policy',
  'privacy-policy',
  'terms-and-conditions',
  'disclaimer',
]);

// Anything starting with "test" is a scratch page — never a nav item, at any level.
const isScratch = (slug) => slug.startsWith('test');

// Hrefs whose auto-prettified label would be wrong.
const LABEL_OVERRIDES = {
  '/sql': 'SQL',
  '/tools/text': 'Text Processing',
};

const cliExcludes = new Set(process.argv.slice(2).map((arg) => arg.replace(/^--/, '')));

function hasIndexFile(dir) {
  return PAGE_EXTENSIONS.some((ext) => fs.existsSync(path.join(dir, `index${ext}`)));
}

function prettify(slug) {
  return slug
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

// Returns the route slug for a directory entry, or null if it isn't a page.
// Dynamic segments ([slug]) are never nav items.
function slugFor(dir, entry) {
  if (entry.name.startsWith('[')) return null;

  if (entry.isDirectory()) {
    return hasIndexFile(path.join(dir, entry.name)) ? entry.name : null;
  }

  const ext = path.extname(entry.name);
  if (!PAGE_EXTENSIONS.includes(ext)) return null;
  return entry.name.slice(0, -ext.length);
}

function labelFor(href, slug) {
  return LABEL_OVERRIDES[href] ?? prettify(slug);
}

const items = [];

for (const entry of fs.readdirSync(PAGES_DIR, { withFileTypes: true })) {
  const slug = slugFor(PAGES_DIR, entry);
  if (!slug || ALWAYS_SKIP.has(slug) || EXCLUDED.has(slug) || cliExcludes.has(slug) || isScratch(slug)) continue;

  const href = `/${slug}`;
  const children = [];

  if (entry.isDirectory()) {
    const dir = path.join(PAGES_DIR, entry.name);
    for (const child of fs.readdirSync(dir, { withFileTypes: true })) {
      const childSlug = slugFor(dir, child);
      if (!childSlug || childSlug === 'index' || isScratch(childSlug)) continue;

      const childHref = `${href}/${childSlug}`;
      children.push({ label: labelFor(childHref, childSlug), href: childHref });
    }
    children.sort((a, b) => a.label.localeCompare(b.label));
  }

  items.push({ label: labelFor(href, slug), href, children });
}

items.sort((a, b) => a.label.localeCompare(b.label));

const entries = items
  .map((item) => {
    const children = item.children
      .map((child) => `      { label: ${JSON.stringify(child.label)}, href: ${JSON.stringify(child.href)} }`)
      .join(',\n');
    const childrenBlock = children ? `[\n${children}\n    ]` : '[]';
    return `  {\n    label: ${JSON.stringify(item.label)},\n    href: ${JSON.stringify(item.href)},\n    children: ${childrenBlock}\n  }`;
  })
  .join(',\n');

const output = `// AUTO-GENERATED by generate-nav.mjs
// Do not edit by hand — this file is overwritten on each build.

const navItems = [
${entries}
];

export default navItems;
`;

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, output);
console.log(`Navigation generated at ${OUTPUT_FILE} (${items.length} items: ${items.map((i) => `${i.label} [${i.children.length}]`).join(', ')})`);
