
// pages/tools/index.jsx
//
// Landing page for the /tools cluster. v2 sidebar design.
//
// Static text — breadcrumb, h1, intro, and the per-category editorial
// widgets (h2, blurb, tips, custom stats) — is rendered directly on this
// page and statically generated. Dynamic data — the full tool list with
// categories — comes from data/home-catalog.js (AUTO-GENERATED by
// generate-home-catalog.mjs v4) through getStaticProps and feeds the
// LandingPage structure component.
//
// The seoData below is also what the generator reads to source this
// pillar's title and blurb for the homepage band.
//
// CLUSTER_WIDGETS: editorial content per category, keyed by the category
// label as it appears in the catalog (prettified). Categories without an
// entry get the component's minimal data-only fallback widget, so a new
// category never breaks the page — it just renders plain until you write
// its widget here.

import fs from 'fs';
import path from 'path';
import Head from 'next/head';
import LandingPage from '@/app/components/landing-page/LandingPage';
import { homeCatalog } from '@/data/home-catalog';
import Breadcrumb from '../../app/components/breadcrumb/Breadcrumb';

const EMPTY_PILLAR = {
  id: 'tools',
  title: 'Tools',
  href: '/tools',
  blurb: '',
  ctaLabel: '',
  stats: [],
  breakdown: [],
  pages: [],
};

// "Other sections" = every top-level folder under pages/ except this one and
// non-section folders. Purely filesystem-driven — a new section folder shows
// up here on the next build with no edits. Only label casing is overridden.
const SECTION_LABEL_OVERRIDES = {
  sql: 'SQL',
  'c-programming': 'C Programming',
};

const NON_SECTION_DIRS = new Set(['api']);

function sectionLabel(slug) {
  if (SECTION_LABEL_OVERRIDES[slug]) return SECTION_LABEL_OVERRIDES[slug];
  return slug
    .split('-')
    .map((w) => (w.length === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1)))
    .join(' ');
}

export async function getStaticProps() {
  const keyWords = [
    'developer tools',
    'online dev tools',
    'json formatter',
    'regex tester',
    'encoder decoder',
    'code minifier',
  ];

  const rawPillar = homeCatalog.pillars.find((p) => p.id === 'tools') || EMPTY_PILLAR;

  // /tools is flat — one level deep. Legacy nested subsection pages
  // (coding-tools/, converters/, tables/) are excluded from the listing;
  // each reappears automatically once rebuilt as a standalone /tools/<slug>
  // page. Stats and breakdown are recomputed from the filtered list.
  const flatPages = (rawPillar.pages || []).filter(
    (p) => p.href.split('/').filter(Boolean).length === 2
  );
  const categoryCounts = new Map();
  for (const p of flatPages) {
    categoryCounts.set(p.category, (categoryCounts.get(p.category) || 0) + 1);
  }
  const breakdown = [...categoryCounts.entries()]
    .map(([label, count]) => ({ label, count }))
    .sort((a, b) => b.count - a.count);

  const pillar = {
    ...rawPillar,
    pages: flatPages,
    breakdown,
    stats: [
      { n: String(flatPages.length), label: 'Pages' },
      { n: String(breakdown.length), label: 'Categories' },
    ],
  };

  const pagesDir = path.join(process.cwd(), 'pages');
  const otherSections = fs
    .readdirSync(pagesDir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter(
      (name) =>
        name !== pillar.id &&
        !name.startsWith('_') &&
        !name.startsWith('[') &&
        !name.startsWith('test') &&
        !NON_SECTION_DIRS.has(name)
    )
    .sort()
    .map((slug) => ({ label: sectionLabel(slug), href: `/${slug}` }));

  return {
    props: {
      pillar,
      secondaryLinks: otherSections,
      seoData: {
        title: 'Developer Tools | WebDevData',
        description:
          'Client-side developer utilities. Fast, keyboard-first, no signup. JSON, encoders, formatters, generators, and converters.',
        keywords: keyWords.join(', '),
        url: '/tools',
        name: 'Tools',
      },
    },
  };
}

export default function ToolsLandingPage({ pillar, seoData, secondaryLinks }) {
  // Editorial widget content per category. Keyed by catalog category label.
  // These are render functions called as widget(cluster), not components —
  // the display-name rule is a false positive here.
  /* eslint-disable react/display-name */
  const CLUSTER_WIDGETS = {
    'JSON Tools': (cluster) => (
      <>
        <div className="wddl-widget-kicker">Category</div>
        <h2>JSON Tools</h2>
        <p className="wddl-widget-blurb">
          The anchor category. Format, view, and transform JSON entirely in the
          browser &mdash; nothing leaves your machine. Every tool takes the same
          input format and links to the next one via the toolbar.
        </p>
        <div className="wddl-widget-stats">
          <div className="wddl-wstat"><span className="wddl-wstat-n">{cluster.count}</span><span className="wddl-wstat-label">Tools</span></div>
          <div className="wddl-wstat"><span className="wddl-wstat-n">50MB</span><span className="wddl-wstat-label">Max input</span></div>
          <div className="wddl-wstat"><span className="wddl-wstat-n">Native</span><span className="wddl-wstat-label">JSON.parse</span></div>
        </div>
        <p className="wddl-widget-note">
          <strong>Tip:</strong> the anchor tool (Formatter) deep-links via{' '}
          <code>?input=</code> so you can share formatted state without any account.
        </p>
      </>
    ),
    Encoders: (cluster) => (
      <>
        <div className="wddl-widget-kicker">Category</div>
        <h2>Encoders</h2>
        <p className="wddl-widget-blurb">
          Encode and decode text formats &mdash; base64, URL, HTML entities, JWT.
          UTF-8 safe throughout. Native browser APIs, no dependencies.
        </p>
        <div className="wddl-widget-stats">
          <div className="wddl-wstat"><span className="wddl-wstat-n">{cluster.count}</span><span className="wddl-wstat-label">Tools</span></div>
          <div className="wddl-wstat"><span className="wddl-wstat-n">UTF-8</span><span className="wddl-wstat-label">Safe</span></div>
          <div className="wddl-wstat"><span className="wddl-wstat-n">Client</span><span className="wddl-wstat-label">Only</span></div>
        </div>
        <p className="wddl-widget-note">
          <strong>Tip:</strong> JWT decoder verifies signatures locally with Web
          Crypto &mdash; paste your secret without worrying about server logs.
        </p>
      </>
    ),
    'Formatters & Minifiers': (cluster) => (
      <>
        <div className="wddl-widget-kicker">Category</div>
        <h2>Formatters &amp; Minifiers</h2>
        <p className="wddl-widget-blurb">
          Two-way tools &mdash; beautify code for reading, minify for shipping.
          Handle every major format: JS, CSS, HTML, SQL, XML. Diff checker to
          compare the before and after.
        </p>
        <div className="wddl-widget-stats">
          <div className="wddl-wstat"><span className="wddl-wstat-n">{cluster.count}</span><span className="wddl-wstat-label">Tools</span></div>
          <div className="wddl-wstat"><span className="wddl-wstat-n">Both ways</span><span className="wddl-wstat-label">Yes</span></div>
          <div className="wddl-wstat"><span className="wddl-wstat-n">5</span><span className="wddl-wstat-label">Formats</span></div>
        </div>
        <p className="wddl-widget-note">
          <strong>Tip:</strong> the SQL formatter has dialect awareness &mdash;
          pick Postgres, MySQL, SQLite, or MSSQL for correct keyword casing and
          identifier quoting.
        </p>
      </>
    ),
    Generators: (cluster) => (
      <>
        <div className="wddl-widget-kicker">Category</div>
        <h2>Generators</h2>
        <p className="wddl-widget-blurb">
          Produce IDs, hashes, HMACs, and boilerplate on demand. Cryptographic
          ones use Web Crypto API &mdash; real primitives, no JavaScript
          reimplementations of MD5 loaded from a CDN.
        </p>
        <div className="wddl-widget-stats">
          <div className="wddl-wstat"><span className="wddl-wstat-n">{cluster.count}</span><span className="wddl-wstat-label">Tools</span></div>
          <div className="wddl-wstat"><span className="wddl-wstat-n">Web Crypto</span><span className="wddl-wstat-label">API</span></div>
          <div className="wddl-wstat"><span className="wddl-wstat-n">Bulk</span><span className="wddl-wstat-label">Support</span></div>
        </div>
        <p className="wddl-widget-note">
          <strong>Tip:</strong> the UUID generator supports ULID and UUIDv7
          alongside v4 &mdash; useful when you need lexicographic ordering with
          your IDs.
        </p>
      </>
    ),
    Converters: (cluster) => (
      <>
        <div className="wddl-widget-kicker">Category</div>
        <h2>Converters</h2>
        <p className="wddl-widget-blurb">
          Move data between formats and units. Timezone-aware timestamps, YAML
          round-tripping, modern color space conversion, dev-friendly units.
        </p>
        <div className="wddl-widget-stats">
          <div className="wddl-wstat"><span className="wddl-wstat-n">{cluster.count}</span><span className="wddl-wstat-label">Tools</span></div>
          <div className="wddl-wstat"><span className="wddl-wstat-n">TZ-aware</span><span className="wddl-wstat-label">Yes</span></div>
          <div className="wddl-wstat"><span className="wddl-wstat-n">oklch</span><span className="wddl-wstat-label">Modern</span></div>
        </div>
        <p className="wddl-widget-note">
          <strong>Tip:</strong> the timestamp converter&apos;s &quot;now&quot; button copies
          both epoch seconds and ISO 8601 to the clipboard at once.
        </p>
      </>
    ),
  };
  /* eslint-enable react/display-name */

  const renderClusterWidget = (cluster) => {
    const widget = CLUSTER_WIDGETS[cluster.category];
    return widget ? widget(cluster) : null; // null → component's data-only fallback
  };

  const totalPages = Array.isArray(pillar.pages) ? pillar.pages.length : 0;
  const totalCategories = Array.isArray(pillar.breakdown) ? pillar.breakdown.length : 0;

  return (
    <>
      <Head>
        <title>{seoData.title}</title>
        <meta name="description" content={seoData.description} />
        <meta name="keywords" content={seoData.keywords} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="canonical" href={`https://www.webdevdata.net${seoData.url}`} />

        <meta property="og:title" content={seoData.title} />
        <meta property="og:description" content={seoData.description} />
        <meta property="og:url" content={`https://www.webdevdata.net${seoData.url}`} />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="WebDevData" />

        <meta name="twitter:card" content="summary" />
        <meta name="twitter:title" content={seoData.title} />
        <meta name="twitter:description" content={seoData.description} />

        <meta name="robots" content="index, follow" />

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'CollectionPage',
              name: seoData.name,
              description: seoData.description,
              url: `https://www.webdevdata.net${seoData.url}`,
              inLanguage: 'en-US',
            }),
          }}
        />
      </Head>
       
      <div className="tools-landing">
        {/* <div className="tl-breadcrumb">
          <a href="/">Home</a><span className="tl-sep">/</span>Tools
        </div> */}
           <br/>
        <br/>
        <br/>
        <Breadcrumb/>
        <div className="tl-page-head">
          <div>
            <h1>Tools</h1>
            <p className="tl-sub">
              Client-side developer utilities. Each category below has its own
              widget with context and stats.
            </p>
          </div>
          <div className="tl-stats">
            <div className="tl-stat"><span className="tl-n">{totalPages}</span><span className="tl-label">Tools</span></div>
            <div className="tl-stat"><span className="tl-n">{totalCategories}</span><span className="tl-label">Categories</span></div>
            <div className="tl-stat"><span className="tl-n">0ms</span><span className="tl-label">Server</span></div>
          </div>
        </div>
    
      
        {/* <LandingPage
          pillar={pillar}
          renderClusterWidget={renderClusterWidget}
          navTitle="On this page"
          secondaryNavTitle="Other sections"
          secondaryLinks={[
            { label: 'Reference', href: '/reference' },
            { label: 'Learn', href: '/learn' },
          ]}
          categoryOrder={['JSON Tools', 'Encoders', 'Formatters & Minifiers', 'Generators', 'Converters']}
          theme="light"
        /> */}
        <LandingPage
          pillar={pillar}
          renderClusterWidget={renderClusterWidget}
          navTitle="On this page"
          secondaryNavTitle="Other sections"
          secondaryLinks={secondaryLinks}
          categoryOrder={['JSON Tools', 'Encoders', 'Formatters & Minifiers', 'Generators', 'Converters']}
          stickyOffset="90px"
          theme="light"
        />
      </div>

      <style jsx>{`
        .tools-landing {
          width: 100%;
        }
        .tl-breadcrumb {
          max-width: 1400px;
          margin: 0 auto;
          padding: 16px 32px 0;
          font-size: 12.5px;
          color: #71717a;
        }
        .tl-breadcrumb a {
          color: #71717a;
          text-decoration: none;
        }
        .tl-breadcrumb a:hover {
          color: #4d4dff;
        }
        .tl-sep {
          margin: 0 6px;
          color: #d4d4d8;
        }
        .tl-page-head {
          max-width: 1400px;
          margin: 0 auto;
          padding: 24px 32px 0;
          display: flex;
          justify-content: space-between;
          align-items: flex-end;
          gap: 32px;
          border-bottom: 1px solid #e4e4e7;
          padding-bottom: 24px;
        }
        .tl-page-head h1 {
          font-size: 32px;
          font-weight: 700;
          color: #09090b;
          letter-spacing: -0.02em;
          margin: 0 0 4px;
          line-height: 1.15;
        }
        .tl-sub {
          color: #52525b;
          font-size: 14px;
          max-width: 520px;
          margin: 0;
        }
        .tl-stats {
          display: flex;
          gap: 24px;
        }
        .tl-n {
          font-size: 22px;
          font-weight: 700;
          color: #4d4dff;
          line-height: 1;
          display: block;
          margin-bottom: 4px;
        }
        .tl-label {
          font-size: 10.5px;
          color: #71717a;
          text-transform: uppercase;
          letter-spacing: 0.06em;
        }

        @media (max-width: 800px) {
          .tl-page-head {
            flex-direction: column;
            align-items: flex-start;
            gap: 16px;
          }
        }
      `}</style>
    </>
  );
}