const prismThemes = {
    a11yDark: 'a11y-dark',
    atomDark: 'atom-dark',
    base16AteliersulphurpoolLight: 'base16-ateliersulphurpool.light',
    cb: 'cb',
    coldarkCold: 'coldark-cold',
    coldarkDark: 'coldark-dark',
    coy: 'coy',
    darcula: 'darcula',
    duotoneDark: 'duotone-dark',
    duotoneEarth: 'duotone-earth',
    duotoneForest: 'duotone-forest',
    duotoneLight: 'duotone-light',
    duotoneSea: 'duotone-sea',
    duotoneSpace: 'duotone-space',
    funky: 'funky',
    ghcolors: 'ghcolors',
    gruvboxDark: 'gruvbox-dark',
    gruvboxLight: 'gruvbox-light',
    holiTheme: 'holi-theme',
    hopscotch: 'hopscotch',
    materialDark: 'material-dark',
    materialLight: 'material-light',
    materialOceanic: 'material-oceanic',
    nightOwl: 'night-owl',
    nord: 'nord',
    okaidia: 'okaidia',
    oneDark: 'one-dark',
    oneLight: 'one-light',
    pojoaque: 'pojoaque',
    prism: 'prism',
    shadesOfPurple: 'shades-of-purple',
    solarizedDarkAtom: 'solarized-dark-atom',
    solarizedlight: 'solarizedlight',
    synthwave84: 'synthwave84',
    tomorrow: 'tomorrow',
    twilight: 'twilight',
    vs: 'vs',
    vscDarkPlus: 'vsc-dark-plus',
    xonokai: 'xonokai',
    zTouch: 'z-touch'
  };
  
  export default prismThemes;