// // // pages/index.jsx
// // //
// // // Homepage. Pure assembler — all content comes from data/home-catalog.js,
// // // which is AUTO-GENERATED by generate-home-catalog.mjs from the seoData
// // // declared inside each page. Add a page → it appears here on next build.
// // //
// // // Layout and theme are selected here; the HomePage template supports
// // // layout: 'zigzag' | 'stacked' and theme: 'light' | 'dark'.

// // import Head from 'next/head';
// // import HomePage from '@/app/components/home-page/HomePage';
// // import { homeCatalog } from '@/data/home-catalog';

// // export async function getStaticProps() {
// //   const heroContent = {
// //     title: 'Everything a web developer looks up.',
// //     subtitle: 'Reference, tools, and tutorials. Fast, clean, modern. Zero ads above the fold, ever.',
// //     searchPlaceholder: 'Search tools, functions, tutorials...',
// //   };

// //   return {
// //     props: {
// //       pillars: homeCatalog.pillars,
// //       heroContent,
// //       seoData: {
// //         title: 'WebDevData | Reference, Tools, and Tutorials for Web Developers',
// //         description:
// //           'Reference, tools, and tutorials for web developers. Fast, clean, and modern. Function references, client-side developer utilities, and how-to guides.',
// //         keywords:
// //           'web development, developer tools, programming reference, javascript, python, sql, css, c programming',
// //         url: '/',
// //         name: 'WebDevData',
// //       },
// //     },
// //   };
// // }

// // export default function Home({ pillars, heroContent, seoData }) {
// //   return (
// //     <>
// //       <Head>
// //         <title>{seoData.title}</title>
// //         <meta name="description" content={seoData.description} />
// //         <meta name="keywords" content={seoData.keywords} />
// //         <meta name="viewport" content="width=device-width, initial-scale=1" />
// //         <link rel="canonical" href={`https://www.webdevdata.net${seoData.url}`} />

// //         <meta property="og:title" content={seoData.title} />
// //         <meta property="og:description" content={seoData.description} />
// //         <meta property="og:url" content={`https://www.webdevdata.net${seoData.url}`} />
// //         <meta property="og:type" content="website" />
// //         <meta property="og:site_name" content="WebDevData" />

// //         <meta name="twitter:card" content="summary" />
// //         <meta name="twitter:title" content={seoData.title} />
// //         <meta name="twitter:description" content={seoData.description} />

// //         <meta name="robots" content="index, follow" />

// //         <script
// //           type="application/ld+json"
// //           dangerouslySetInnerHTML={{
// //             __html: JSON.stringify({
// //               '@context': 'https://schema.org',
// //               '@type': 'WebSite',
// //               name: seoData.name,
// //               description: seoData.description,
// //               url: 'https://www.webdevdata.net/',
// //               inLanguage: 'en-US',
// //             }),
// //           }}
// //         />
// //       </Head>

// //       <HomePage
// //         pillars={pillars}
// //         hero={heroContent}
// //         layout="zigzag"
// //         theme="light"
// //       />
// //     </>
// //   );
// // }


// // pages/index.jsx
// //
// // Homepage. Pure assembler — all content comes from data/home-catalog.js,
// // which is AUTO-GENERATED by generate-home-catalog.mjs from the seoData
// // declared inside each page. Add a page → it appears here on next build.
// //
// // The h1 and the per-pillar h2 elements are declared HERE, in the page —
// // the HomePage template only positions and styles them. Heading semantics
// // belong to the page, not the component.
// //
// // Layout and theme are selected here; the HomePage template supports
// // layout: 'zigzag' | 'stacked' and theme: 'light' | 'dark'.

// import Head from 'next/head';
// import HomePage from '@/app/components/home-page/HomePage';
// import { homeCatalog } from '@/data/home-catalog';

// export async function getStaticProps() {
//   const heroContent = {
//     subtitle: 'Reference, tools, and tutorials. Fast, clean, modern. Zero ads above the fold, ever.',
//     searchPlaceholder: 'Search tools, functions, tutorials...',
//   };

//   return {
//     props: {
//       pillars: homeCatalog.pillars,
//       heroContent,
//       seoData: {
//         title: 'WebDevData | Reference, Tools, and Tutorials for Web Developers',
//         description:
//           'Reference, tools, and tutorials for web developers. Fast, clean, and modern. Function references, client-side developer utilities, and how-to guides.',
//         keywords:
//           'web development, developer tools, programming reference, javascript, python, sql, css, c programming',
//         url: '/',
//         name: 'WebDevData',
//       },
//     },
//   };
// }

// export default function Home({ pillars, heroContent, seoData }) {
//   return (
//     <>
//       <Head>
//         <title>{seoData.title}</title>
//         <meta name="description" content={seoData.description} />
//         <meta name="keywords" content={seoData.keywords} />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="canonical" href={`https://www.webdevdata.net${seoData.url}`} />

//         <meta property="og:title" content={seoData.title} />
//         <meta property="og:description" content={seoData.description} />
//         <meta property="og:url" content={`https://www.webdevdata.net${seoData.url}`} />
//         <meta property="og:type" content="website" />
//         <meta property="og:site_name" content="WebDevData" />

//         <meta name="twitter:card" content="summary" />
//         <meta name="twitter:title" content={seoData.title} />
//         <meta name="twitter:description" content={seoData.description} />

//         <meta name="robots" content="index, follow" />

//         <script
//           type="application/ld+json"
//           dangerouslySetInnerHTML={{
//             __html: JSON.stringify({
//               '@context': 'https://schema.org',
//               '@type': 'WebSite',
//               name: seoData.name,
//               description: seoData.description,
//               url: 'https://www.webdevdata.net/',
//               inLanguage: 'en-US',
//             }),
//           }}
//         />
//       </Head>
//  <br/>
//  <br/>
//  <br/>
//  <br/>
//       <HomePage
//         pillars={pillars}
//         hero={heroContent}
//         heading={
//           <h1 className="wdd-hero-h1">Everything a web developer looks up.</h1>
//         }
//         renderPillarHeading={(pillar) => (
//           <h2 className="wdd-cat-h2">{pillar.title}</h2>
//         )}
//         layout="zigzag"
//         theme="light"
//       />
//     </>
//   );
// }


// pages/index.jsx
//
// Homepage. Static text (h1, hero paragraph) is rendered directly on the
// page and styled here. Dynamic pillar data comes from data/home-catalog.js
// (AUTO-GENERATED by generate-home-catalog.mjs) through getStaticProps and
// is passed to the HomePage structure component.

import Head from 'next/head';
import HomePage from '@/app/components/home-page/HomePage';
import { homeCatalog } from '@/data/home-catalog';

export async function getStaticProps() {
  return {
    props: {
      pillars: homeCatalog.pillars,
    },
  };
}

export default function Home({ pillars }) {
  return (
    <>
      <Head>
        <title>WebDevData | Reference, Tools, and Tutorials for Web Developers</title>
        <meta
          name="description"
          content="Reference, tools, and tutorials for web developers. Fast, clean, and modern. Function references, client-side developer utilities, and how-to guides."
        />
        <meta
          name="keywords"
          content="web development, developer tools, programming reference, javascript, python, sql, css, c programming"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="canonical" href="https://www.webdevdata.net/" />

        <meta property="og:title" content="WebDevData | Reference, Tools, and Tutorials for Web Developers" />
        <meta
          property="og:description"
          content="Reference, tools, and tutorials for web developers. Fast, clean, and modern."
        />
        <meta property="og:url" content="https://www.webdevdata.net/" />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="WebDevData" />

        <meta name="twitter:card" content="summary" />
        <meta name="twitter:title" content="WebDevData | Reference, Tools, and Tutorials for Web Developers" />
        <meta
          name="twitter:description"
          content="Reference, tools, and tutorials for web developers. Fast, clean, and modern."
        />

        <meta name="robots" content="index, follow" />

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'WebSite',
              name: 'WebDevData',
              description:
                'Reference, tools, and tutorials for web developers. Fast, clean, and modern.',
              url: 'https://www.webdevdata.net/',
              inLanguage: 'en-US',
            }),
          }}
        />
      </Head>
  <br/>
  <br/>
  <br/>
      <div className="home">
        <section className="hero">
          <h1>Everything a web developer looks up.</h1>
          <p className="hero-sub">
            Reference, tools, and tutorials. Fast, clean, modern. Zero ads above the fold, ever.
          </p>
        </section>

        <main className="pillars">
          <HomePage
            pillars={pillars}
            layout="zigzag"
            theme="light"
            searchPlaceholder="Search tools, functions, tutorials..."
          />
        </main>
      </div>

      <style jsx>{`
        .home {
          width: 100%;
        }

        /* ── HERO ── */
        .hero {
          max-width: 1240px;
          margin: 0 auto;
          padding: 64px 32px 0;
          text-align: center;
        }
        .hero h1 {
          font-size: 44px;
          font-weight: 700;
          letter-spacing: -0.03em;
          margin: 0 0 14px;
          color: #09090b;
          line-height: 1.1;
        }
        .hero-sub {
          color: #52525b;
          font-size: 17px;
          max-width: 560px;
          margin: 0 auto;
          line-height: 1.55;
        }

        @media (max-width: 640px) {
          .hero {
            padding: 48px 24px 0;
          }
          .hero h1 {
            font-size: 32px;
          }
        }
      `}</style>
    </>
  );
}