import MyNavbar from '@/app/components/nav-bar/MyNavbar';
import './pages.css';

const PrivacyPolicy = () => {
  return (
    <>
      <MyNavbar />
      <br />
      <br />
      <div style={{ padding: '100px' }}>
        <div className='title'>
          <h1>Privacy Policy</h1>
          <p>Last updated: June 16, 2024</p>
          <br />
          <br />
        </div>
        <p>This Privacy Policy outlines our policies on the collection, use, and disclosure of your information when you use our Service, and informs you about your privacy rights and how the law protects you. By using the Service, you consent to the processing of information in accordance with this Privacy Policy.</p>
        
        <h2>Interpretation and Definitions</h2>
        <h3>Interpretation</h3>
        <p>The terms in which the initial letter is capitalized are defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural form.</p>
        
        <h3>Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul>
          <li><strong>Account</strong> means a unique account created for you to access our Service or parts of our Service.</li>
          <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.</li>
          <li><strong>Application</strong> refers to Webdevdata, the software program provided by the Company.</li>
          <li><strong>Company</strong> (referred to as either &quot;the Company,&quot; &quot;We,&quot; &quot;Us,&quot; or &quot;Our&quot; in this Agreement) refers to Webdevdata, located in Israel. Our commitment extends to compliance with international data protection regulations such as GDPR for users in the European Union and CCPA for users in California, USA.</li>
          <li><strong>Cookies</strong> are small files placed on your device by a website, containing details of your browsing history among its many uses.</li>
          <li><strong>Country</strong> refers to Israel, where the Company is headquartered. Our services are globally oriented and compliant with applicable international laws.</li>
          <li><strong>Device</strong> means any device that can access the Service, such as a computer, a cellphone, or a digital tablet.</li>
          <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service</strong> refers to the Application or the Website or both.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes data on behalf of the Company. This includes third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.</li>
          <li><strong>Third-party Social Media Service</strong> refers to any website or social network website through which a User can log in or create an account to use the Service.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li><strong>Website</strong> refers to Webdevdata, accessible from <a href="https://www.webdevdata.net" rel="external nofollow noopener" target="_blank">https://www.webdevdata.net</a></li>
          <li><strong>You</strong> refers to the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h2>Collecting and Using Your Personal Data</h2>
        <h3>Types of Data Collected</h3>
        <h4>Personal Data</h4>
        <p>While using Our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</p>
        <ul>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <h4>Usage Data</h4>
        <p>Usage Data is collected automatically when using the Service. This may include information such as your device&apos;s Internet Protocol address, browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.</p>
        <p>When you access the Service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device&apos;s unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, and other diagnostic data.</p>

        <h4>Information from Third-Party Social Media Services</h4>
        <p>The Company allows you to create an account and log in to use the Service through the following Third-party Social Media Services: Google, Facebook, Instagram, Twitter, and LinkedIn.</p>
        <p>If you decide to register through or otherwise grant us access to a Third-Party Social Media Service, we may collect Personal data that is already associated with your Third-Party Social Media Service&apos;s account, such as your name, your email address, your activities, or your contact list associated with that account.</p>

        <h4>Tracking Technologies and Cookies</h4>
        <p>We use Cookies and similar tracking technologies to track the activity on our Service and store certain information. Technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service. We use both session and persistent Cookies for the purposes set out below:</p>
        <ul>
          <li><strong>Necessary / Essential Cookies</strong>: Type: Session Cookies. Administered by: Us. Purpose: These Cookies are essential to provide you with services available through the Website and to enable you to use some of its features.</li>
          <li><strong>Cookies Policy / Notice Acceptance Cookies</strong>: Type: Persistent Cookies. Administered by: Us. Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li>
          <li><strong>Functionality Cookies</strong>: Type: Persistent Cookies. Administered by: Us. Purpose: These Cookies allow us to remember choices you make when you use the Website, such as remembering your login details or language preference.</li>
        </ul>

        <h3>Use of Your Personal Data</h3>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul>
          <li><strong>To provide and maintain our Service</strong>: Including to monitor the usage of our Service.</li>
          <li><strong>To manage Your Account</strong>: Your registration as a user of the Service. The Personal Data you provide can give you access to different functionalities of the Service that are available to you as a registered user.</li>
          <li><strong>For the performance of a contract</strong>: The development, compliance, and undertaking of the purchase contract for the products, items, or services you have purchased or of any other contract with us through the Service.</li>
          <li><strong>To contact You</strong>: To contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
          <li><strong>To provide You with news, special offers, and general information about other goods, services, and events which we offer</strong>: That are similar to those that you have already purchased or enquired about unless you have opted not to receive such information.</li>
          <li><strong>To manage Your requests</strong>: To attend and manage your requests to us.</li>
          <li><strong>For business transfers</strong>: We may use your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by us about our Service users is among the assets transferred.</li>
          <li><strong>For other purposes</strong>: We may use your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing, and your experience.</li>
        </ul>

        <h3>Retention of Your Personal Data</h3>
        <p>The Company will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
        <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>

        <h3>Transfer of Your Personal Data</h3>
        <p>Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. This means that this information may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those from your jurisdiction.</p>
        <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
        <p>The Company will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

        <h3>Delete Your Personal Data</h3>
        <p>You have the right to delete or request that we assist in deleting the Personal Data that we have collected about you.</p>
        <p>Our Service may give you the ability to delete certain information about you from within the Service.</p>
        <p>You may update, amend, or delete your information at any time by signing in to your Account, if you have one, and visiting the account settings section that allows you to manage your personal information. You may also contact us to request access to, correct, or delete any personal information that you have provided to us.</p>
        <p>Please note, however, that we may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>

        <h3>Disclosure of Your Personal Data</h3>
        <h4>Business Transactions</h4>
        <p>If the Company is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
        <h4>Law enforcement</h4>
        <p>Under certain circumstances, the Company may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).</p>
        <h4>Other legal requirements</h4>
        <p>The Company may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul>
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
          <li>Protect the personal safety of Users of the Service or the public</li>
          <li>Protect against legal liability</li>
        </ul>

        <h3>Security of Your Personal Data</h3>
        <p>The security of your Personal Data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

        <h2>Children&apos;s Privacy</h2>
        <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from anyone under the age of 13 without verification of parental consent, we take steps to remove that information from our servers.</p>
        <p>If we need to rely on consent as a legal basis for processing your information and your country requires consent from a parent, we may require your parent&apos;s consent before we collect and use that information.</p>

        <h2>Links to Other Websites</h2>
        <p>Our Service may contain links to other websites that are not operated by us. If you click on a third party link, you will be directed to that third party&apos;s site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
        <p>We have no control over and assume no responsibility for the content, privacy policies, or practices of any third party sites or services.</p>

        <h2>Changes to this Privacy Policy</h2>
        <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
        <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
        <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

        <h2>Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, you can contact us:</p>
        <ul>
          <li>By email: alexkha@netvision.net.il</li>
        </ul>
      </div>
    </>
  );
};

export default PrivacyPolicy;
